# Model configuration

# Common settings for all models
common:
  random_state: 42
  n_jobs: -1  # Use all available cores

# Models to train and their hyperparameters
models:
  linear_regression:
    enabled: true
    params: {}
    hyperparameter_tuning:
      enabled: false
      
  ridge_regression:
    enabled: true
    params:
      alpha: 1.0
    hyperparameter_tuning:
      enabled: true
      param_grid:
        alpha: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
  
  lasso_regression:
    enabled: true
    params:
      alpha: 0.1
    hyperparameter_tuning:
      enabled: true
      param_grid:
        alpha: [0.001, 0.01, 0.1, 1.0, 10.0]
        max_iter: [1000, 2000]
  
  elastic_net:
    enabled: true
    params:
      alpha: 0.1
      l1_ratio: 0.5
    hyperparameter_tuning:
      enabled: true
      param_grid:
        alpha: [0.001, 0.01, 0.1, 1.0]
        l1_ratio: [0.1, 0.3, 0.5, 0.7, 0.9]
  
  random_forest:
    enabled: true
    params:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
    hyperparameter_tuning:
      enabled: true
      param_grid:
        n_estimators: [50, 100, 200]
        max_depth: [5, 10, 15, 20, null]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
  
  gradient_boosting:
    enabled: true
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
    hyperparameter_tuning:
      enabled: true
      param_grid:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.05, 0.1]
        max_depth: [3, 5, 7]
  
  xgboost:
    enabled: true
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 5
      subsample: 0.8
      colsample_bytree: 0.8
    hyperparameter_tuning:
      enabled: true
      param_grid:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.05, 0.1]
        max_depth: [3, 5, 7]
        subsample: [0.7, 0.8, 0.9]
        colsample_bytree: [0.7, 0.8, 0.9]
  
  lightgbm:
    enabled: true
    params:
      n_estimators: 100
      learning_rate: 0.1
      num_leaves: 31
      feature_fraction: 0.8
    hyperparameter_tuning:
      enabled: true
      param_grid:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.05, 0.1]
        num_leaves: [15, 31, 63]
        feature_fraction: [0.7, 0.8, 0.9]

  adaptive_classifier:
    enabled: true
    models_config:
      low_temp:
        range: [-inf, 15.0]
        model: random_forest
        params:
          n_estimators: 150
      medium_temp:
        range: [15.0, 25.0]
        model: gradient_boosting
        params:
          n_estimators: 100
      high_temp:
        range: [25.0, inf]
        model: xgboost
        params:
          n_estimators: 100
    default_model:
      model: random_forest
      params:
        n_estimators: 100

# Model evaluation metrics for regression problem
evaluation_regression:
  metrics:
    - r2
    - mae
    - mse
    - rmse
  primary_metric: rmse  # Metric used for model selection
  lower_is_better: true  # For primary metric

# Model evaluation metrics for classification problem
evaluation_classification:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  primary_metric: accuracy  # Metric used for model selection
  lower_is_better: false  # For primary metric